spring.application.name: logly-batch
spring.profiles.active: local

spring:
  config:
    import:
      - database.yml
      - logging.yml

---
spring.config.activate.on-profile: local




---
spring.config.activate.on-profile: prod

