services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: logly
      MYSQL_USER: jungmini
      MYSQL_PASSWORD: qwer1234
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - logly

networks:
  logly:
    driver: bridge